#!/bin/sh
#
# Git Hook
# Updates the working copy and reconfigure the server.
#

git-update-server-info

echo "Running pull in $HOME/conf..."
# One of the very many Git WTF's
cd $HOME/conf && env -i git pull

echo "Running config engine..."
pomodoro-server
